# プレゼンテーション

これまで、いろいろな図を作ってきたかと思います。
そして、それは .Rmd 形式のファイルに保存していました。

自分のPCにだけ保存しておくのはもったいないです。
ぜひ、クラスで発表してみましょう。

## レポートを作成

今まで、Rmd をたくさん作ってきたかと思います。

knit ボタンを使って、レポートを作成して見ましょう。

出力形式は、ホームページを作る HTML 形式と、Microsoft Word 形式などを選ぶことができます。



## プレゼンテーション

Rmd でプレゼンテーションファイルが作れます。
実は、Rmd からスライドを作る方法はたくさんあります。

* PowerPoint 出力
* HTML 出力
  * ioslides
  * Slidify
  * reveal.js

それぞれ、見た目や機能が異なりますので、試してみて気に入ったものを使ってみてください。ここでは、ioslides を試してみます。

メニューから

File &gt; New File &gt; R Markdown... &gt; Presentation

とし、HTML (ioslides) とすれば、必要に応じて必要なパッケージをインストールします。

### Rmd ファイルを作成

Rmd を作成し、最初の４〜５行目を書き換えます。

```{}
---
title: タイトル
author: 馬場美彦
date: 日付
output: ioslides_presentation
---
```


Rmd ファイルでは、スライドの区切りは、以下のようになります。

* 大見出しを付ける場合は `#`
* 見出しを付ける場合は `##`
* 見出しのないスライドの区切りは `---`

<div class="sourceRmd">
\# 見出し1

一つ目のスライド

\#\# 小見出し1

二つ目のスライド

\-\-\-

三つ目のスライド

\-\-\-

四つ目のスライド

p を押してみてください。

&lt;div class="notes"&gt;
これが表示されます。
&lt;/div&gt;

\-\-\-

\`\`\`{r echo = FALSE}

library(ggplot2)

ggplot(dfKentei4, aes(x = やま, y = たかさ)) +
  geom_bar(stat = "identity")

\`\`\`
</div>

## まとめ

* スライド作成をすることができました。